server:
  port: 8082

spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/zukexing?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:

mybatis:
  # MyBatis解析设置
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.zukexing.pojo